version: '3.8'

services:
  person-intel-crawler:
    build:
      context: .
      dockerfile: Dockerfile
    image: person-intel-crawler:latest
    container_name: person-intel-crawler
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.cache:/app/.cache
    env_file:
      - .env
    environment:
      - LOG_LEVEL=INFO
    command: ["John Doe", "--output", "/app/data/results.json"]

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: person-intel-crawler-api:latest
    container_name: person-intel-crawler-api
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.cache:/app/.cache
    env_file:
      - .env
    environment:
      - LOG_LEVEL=INFO
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
  
  ui:
    build:
      context: ./UI
      dockerfile: Dockerfile
    image: person-intel-crawler-ui:latest
    container_name: person-intel-crawler-ui
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_AUTH_ENABLED=false
    depends_on:
      - api